# Generated by Django 3.0.7 on 2020-06-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='morpheme',
            name='negative_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morpheme',
            name='positive_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morpheme',
            name='words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
